### ISSUE TITLE
'Classify' broken

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#109]
Hey, I see you guys rebooted Panoptes and the Front End. Looking pretty! 

But not functional. :disappointed: If I put together a simple, simple project, I get error messages like this when I try to classify:
```
Error: There was a problem on the server. https://panoptes-staging.zooniverse.org/api/subjects?project_id=12&workflow_id=11&sort=cellect → 500
```

We really, really need functionality to do alpha testing. What's the timeline look like, @brian-c ?

**Comment by brian-c** [comment]
That's a back-end issue with cellect. I think it's @camallen's immediate priority, so, soon.

In the meantime I've added a flag to bypass cellect: http://demo.zooniverse.org/panoptes-front-end/?cellect-0#/

**Comment by camallen** [comment]
This should be fixed today.

**Comment by camallen** [comment]
This should be fixed now. If you get thsi error still you need to blow away you're session. Easiest way is to log in and log out. If you're no authenticated then just remove the session cookie.

There is another bug in subject selection but it's not related to the cellect server, https://github.com/zooniverse/Panoptes/issues/554

**Comment by brian-c** [comment]
@camallen Are you sure that issue isn't Cellect-related? With `?cellect=0` I get subjects, but when cellect is enabled the list comes back empty.

**Comment by camallen** [comment]
Yeah - cellect returns a list of unseen subject correctly. Panoptes then uses those id's in a query that basically states we don't have read permission on those subjects. It's a little funky and i'm starting to work on speccing it out (I debugged it the other day when working on cellect stuff).

**Comment by mkosmala** [comment]
@camallen @brian-c It is still not working for me. I have signed out, closed my browser, opened the browser again, signed back in, made a new project, and I still get the cellect error. Maybe it's because my subject isn't 'linking' at project creation? 
```
Review and complete
	General info and science case
1	Subjects
1	Workflow tasks

    Saving project
    Saved project
    Saving subject set
    Saved subject set
    Saving workflow
    Saved workflow
    Saving subject portalsworth.jpg
    Saved subject portalsworth.jpg
    Uploading portalsworth.jpg
    Linking 1 subjects to subject set
    Error: Failed to link 1 subjects!
    Uploaded portalsworth.jpg
```

**Comment by camallen** [comment]
Can you try it in another browser?

**Comment by mkosmala** [comment]
Yup. Was in Firefox. Just tried in Chrome. Same problem.

**Comment by camallen** [comment]
I'm not sure what is happening in the text you sent. Is this output from a script? 

Can you provide the API calls you're making to do all this?

**Comment by camallen** [comment]
what is the URL and are you manually hitting the API?

**Comment by mkosmala** [comment]
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/SecondFeb19Proj/classify?workflow=21

**Comment by mkosmala** [comment]
No, not manual. Just using a browser.

**Comment by mkosmala** [comment]
Oh, and the output I listed is what I see after creating a project. It's the "review" screen that you get after hitting "create".

**Comment by camallen** [comment]
I think you'll need to open a new issue for the linking subjects one.

**Comment by brian-c** [comment]
Make sure `?cellect=0` is still in there.

The subject linking issue will be solved by exposing the `ETag` header.

**Comment by camallen** [comment]
@mkosmala you're project is private. I need to dig into this a little more. Cellect could be erroring if there are no subjects to load. It could be panoptes getting an empty set back from cellect, i'm not sure. Ideally both should be able to handle this.

**Comment by mkosmala** [comment]
Right, sorry. Forgot about the ?cellect=0. This URL works:
http://demo.zooniverse.org/panoptes-front-end/?cellect=0#/projects/mkosmala/SecondFeb19Proj/classify?workflow=21

**Comment by camallen** [comment]
I've found problem with cellect, we were using the non-panoptes specific version. https://github.com/zooniverse/infrastructure/pull/11

Once this is redeployed i'll look into more specific errors if they are sitll occuring.
