### ISSUE TITLE
Implement Recents Page (like Ouroboros) for a PFE project

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2251]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

There must be a page that gives an overview of everything that has recently changed: recent posts, recent tags/comments on subject.

Similar to https://talk.snapshotserengeti.org/#/recent

It must show recent content filtered to just the context of the current project

Posts should show snippets and subjects should show thumbnails - separately - rather than the current page which shows everything big.

Pagination vs "Load more" : Since we have more than one list on the page, "Load more" makes more sense in this specific case.

**Comment by alexbfree** [comment]
This may also solve, address or overlap with #726, #1514, #1522 and #2165

**Comment by alexbfree** [comment]
Am now actively working on this. Developing as separate page but it may get integrated with the existing Recent Comments page.

**Comment by alexbfree** [comment]
Work in progress (functional but unstyled) is at https://recent-page.pfe-preview.zooniverse.org/projects/alexbfree/computer-vision-serengeti/recent?env=production (`recent-page` branch on alexbfree's PFE fork)

**Comment by jwbmartin** [comment]
I definitely agree with what @marten had said in Slack that the buttons could use some styling but I guess what I'm more concerned about is this something that users actually use or just the research team? I guess that is more a question for @mrniaboc?

**Comment by mschwamb** [comment]
@alexbfree is this replacing the recent comments page on Talk?   All the closed ticket of mine, @parrish and Alex W addressed in Talk and the Recent Comment Talk Page. I'm not sure how this serves a different purpose. Also @parrish made specific design decisions in the Recent Comments page to address some of the feedback on the previous Talk Recents page which I've found incrediably useful. Maybe it would be better to merge some of the elements here into the Recent Comments page. 

As a science team member, I wouldn't use this page as although it's graphically pleasing form, the functionality of the recent comments page on Talk is better/more useful in my opinion. The Talk Recent Comments page shows the full comment and text gets shown for the new post and there is a way off filtering text comments easily from the subject page notes/comments. The reason that's important is that a science team and moderators  can read through the comments and see where they need to interject without having to click on each discussion. In your setup, I can't read the full comment, so I'd need to click on each one to read the comment, which means I will miss more. 

Although you separate out the non-Notes threads, you make that less focus and only show one of the comments and don't make them linkable. With the recent comments Talk page, I can toggle off the notes threads, which means I see all text for those threads. That's really important especially when there is a spike in classifications like a press release, but then you can quickly see Help messages or posts about something wrong with the site and alert the developers. 

Also adding this link in navigation bar rather than on Talk means less room for science team links like a blog.  

I can see elements of this page being useful, but I think for the reasons above science team and volunteers  use the recent comment page on Talk more than this.  

I hope the feedback is useful.

**Comment by trouille** [comment]
@jwbmartin https://talk.snapshotserengeti.org/ is how snapshot serengeti uses this functionality. Other ecology survey tool users would benefit from this and use it (e.g., Snapshot WI, Chicago Wildlife Watch, etc. have mentioned this need as well). 

The difference with the approach here is that it's a tab within the Project level and not within Talk (which is where it lives in Snapshot Serengeti). What do you think of that choice, to add another tab to the Project level and not be part of the 'conversation' context of Talk?

**Comment by eatyourgreens** [comment]
@trouille as @mschwamb suggests, wouldn't we be better off updating the existing Talk recents page eg. https://www.zooniverse.org/projects/panthera-research/camera-catalogue/talk/recents since that includes improvements based on feedback from the older Talk.

>As a science team member, I wouldn't use this page as although it's graphically pleasing form, the functionality of the recent comments page on Panoptes Talk is better/more useful in my opinion.

**Comment by parrish** [comment]
I still don't get it, really.  This already exists in a different presentation.  https://www.zooniverse.org/projects/zooniverse/radio-meteor-zoo/talk/recents

The very slight difference is that you can't currently view **only** subject comments.  It would only require changing the "Show subject notes" checkbox into radio buttons for "Show only subject notes, Hide subject notes, Show all."  Which is pretty silly considering the ratio of board to subject comments.  Beyond that, it's simply a cosmetic difference.

**Comment by trouille** [comment]
yes @parrish @eatyourgreens @mschwamb I'm in agreement here with you.

**Comment by jwbmartin** [comment]
Yeah I'm a little confused by this too because I have some people saying researchers would use this but @mschwamb as a researcher saying she wouldn't so I'm wondering if we are creating a function that helps a handful of people while creating more clutter and confusion for the majority of our users.

**Comment by mschwamb** [comment]
@parrish the check mark is there because the ratio changes when the site gets flooded like during launch or BBC stargazing live, and then the subject notes drown out any help/trouble shooting board posts.  I've used the check mark to hid the subject notes when Comet Hunters on BBC Sky at Night. 

The other difference is that on Panoptes (recent Talk) @parrish designed it to  the full comment so I can read and then decide if I need to comment, where in this new page, it shows a snippet of the conversation which have the same problem of I now need to click on each one to read it (and then the scientists don't read a majority of the recent notes and miss stuff)

**Comment by mschwamb** [comment]
To me this duplicates the front page of Talk 2.0 without addressing the things that didn't work well about it or taking advantage of the new things that exist in Panoptes Talk.  But there was iteration with a few people who do science stuff when @parrish wrote the Recent Comments Talk Page, and I think he put a lot of thought into what things worked and didn't work on Talk 2.0. 

Whatever you do, please do not remove the functionality in the Recent Comments Talk page on Talk. All of Talk could use a graphic design touch perhaps to make something look a bit prettier, but in my opinion the Recent Comments Talk page is in my top 2 best things/improvements in panoptes over previous  version of the Zooniverse platform. I use that page every day. 

It sounds like to me that perhaps these other science teams don't know that this feature exists/hasn't looked at it on Talk and are just going off of what they see on the front page. I'm not sure adding a tab on the top of the project menu will help with that. I know most of my science teams don't explore the functionality on the site as they should sometimes, and usually when they say a feature isn't there it's because they haven't looked.

**Comment by parrish** [comment]
> the check mark is there because the ratio changes

Yep, I'm just saying that this proposal could be accomplished by adding the inverse (show only subject comments) as well.  I find it strange to want that since there are usually many more subject comments than board comments.  Also, there is a recents view for each board.  So, the [notes recents](https://www.zooniverse.org/projects/zooniverse/radio-meteor-zoo/talk/recents/422) will basically cover that feature.

> To me this duplicates the front page of Talk 2.0

I completely agree.  In my opinion, this is likely the case of somebody feeling like they "lost" a feature or disliking change in general.  It is in fact still there and (hopefully) more usable than it was.

> It sounds like to me that perhaps these other science teams don't know that this feature exists/hasn't looked at it on Talk and are just going off of what they see on the front page of Talk

Possibly, but I think it could also be not liking something unfamiliar -- which is fair too.

All of that said, I'd rather spend time identifying use cases and building for them.

Revisiting the design of the recents page (there wasn't any other than basic usability) would probably help too.

A good compromise might be to start by using thumbnails for images on the recents page.

**Comment by jwbmartin** [comment]
>>To me this duplicates the front page of Talk 2.0
>I completely agree. In my opinion, this is likely the case of somebody feeling like they "lost" a feature or disliking change in general. It is in fact still there and (hopefully) more usable than it was.

On the same page.

**Comment by mschwamb** [comment]
> Yep, I'm just saying that this proposal could be accomplished by adding the inverse (show only subject comments) as well. I find it strange to want that since there are usually many more subject comments than board comments. Also, there is a recents view for each board. So, the notes recents will basically cover that feature.

Makes sense @parrish . Feel free to change that on the Recent Comments page now if you like. As long as there's a way to display only subject threads for spikes in traffic, then I'm happy.

> A good compromise might be to start by using thumbnails for images on the recents page.

I actually appreciate the larger size of the subject images on the panoptes Recent Comments page. I thought it a was a nice improvement since I could see what was going on in the subject  especially on Planet Four: Terrains, but maybe  you could make them a smaller but not as small as a thumbnail. 

I think if you're looking for areas for improved layout/visual design one area might be Talk subject pages (https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/subjects/2086755). The functionality is all there, but I think some small design tweaks would make it even more usable/user friendly.  For example, currently when you type a comment you can't see the subject image at the same time, so making the subject image smaller there  might be helpful or moving the comment box to right under the subject or something along those lines.

**Comment by srallen** [comment]
Closing... sounds like the original suggestion in this issue was decided as not needed. Any other suggestions in this should be opened as separate issues.
