### ISSUE TITLE
Tool icons appear white on white background in Firefox/Ubuntu, no matter what colour theme selected

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#4902]
## Expected behavior
To have black tool icons on white background (to be able to see them) like in Chromium browser.

## Current behavior
When using a dark Ubuntu theme, the tool icons appear white on white background, no matter whether light or dark theme is set on the project. Only happens in Firefox.

## Screenshots 
Notice the Pan/Zoom-in/Rotate icons - they're white and so not visible (unlike Annotate/Zoom-out/Reset Zoom levels)
Light colour theme
![ysh_screenshot_2018-09-16_white_on_white](https://user-images.githubusercontent.com/7211888/45596300-6edf8c80-b9ba-11e8-9a03-5f270c13893d.png)

Dark colour theme
![ysh_screenshot_2018-09-16_white_on_white_dark](https://user-images.githubusercontent.com/7211888/45596302-730baa00-b9ba-11e8-9a3d-5988353b1636.png)

- **Operating system:**
Ubuntu
- **Browser:**
Firefox 62

(Happens in Ouroboros projects as well, but I see that's just something we'll have to live with until the projects are moved to Panoptes / finished.)

**Comment by srallen** [comment]
Those should be inheriting the font color from styled defined in the parent container. I checked Firefox on OS X and so this is likely a bug unique to FF on Ubuntu (or Linux)

**Comment by srallen** [comment]
Likely fixed by specifying the font color for the button rather than relying on inheritance.

**Comment by srallen** [comment]
@yshish is the color fixed if you use this link? https://fix-4902.pfe-preview.zooniverse.org/projects/penguintom79/penguin-watch/classify?env=production

**Comment by camallen** [comment]
I can't replicate the issue on my ubuntu 16.04.5 with FF 62 though i assume that is because i am not setting the 'dark' theme correctly I'm using 'Ambience' theme by default. 

@yshish which dark ubuntu theme are you using? How can i set the same one? Also which ubuntu version are you running? `lsb_release -a`

**Comment by srallen** [comment]
@camallen I think she means the light and dark themes in the classifier, not OS set color themes. I could be wrong though.

**Comment by yshish** [comment]
> @yshish is the color fixed if you use this link? https://fix-4902.pfe-preview.zooniverse.org/projects/penguintom79/penguin-watch/classify?env=production

Nope, still the same white icons on white background.

> I can't replicate the issue on my ubuntu 16.04.5 with FF 62 though i assume that is because i am not setting the 'dark' theme correctly I'm using 'Ambience' theme by default.
> 
> @yshish which dark ubuntu theme are you using? How can i set the same one? Also which ubuntu version are you running? `lsb_release -a`

I'm running Ubuntu 18.04.1 LTS, xfce; the dark style is called 'Adwaita-dark' - I set it by going to 'Settings manager' and then choosing 'Appearance'. The Adwaita-dark is one from the list.

But I think that we had this issue before, on Ouroboros. And that it was solved by specifying the font colour. The issue should be somewhere on Github, perhaps under Plankton Portal. 

(Sorry, I am super-busy today, I can look for it later tonight/tomorrow.)
